necst-telescope/observer

.devcontainer/devcontainer.json, README.md, observer/server.py, observer/static/index.js, observer/static/quick-look.js, observer/templates/index.html
**Checks**
This PR closes #18.
=> Support background execution

README.md, observer/server.py, observer/static/chart.js, observer/templates/config/edit.html, observer/templates/config/index.html, observer/templates/header.html, observer/templates/index.html, observer/templates/qlook/index.html, poetry.lock, pyproject.toml
**Checks**
This PR closes #20.
=> Serve parameter/configuration files

.devcontainer/Dockerfile, observer/static/chart.js, observer/templates/qlook/index.html, pyproject.toml
**Checks**
This PR closes #23.
=> Version 0.1.1

observer/client_manager.py, observer/server.py, observer/static/index.js
**Checks**
This PR closes #27.
=> Fix namespace specification

pyproject.toml
**Checks**
This PR closes #29.
=> Version 0.1.2

.devcontainer/Dockerfile, Dockerfile, README.md, observer/templates/config/edit.html, observer/templates/config/index.html, pyproject.toml
**Checks**
This PR closes #25.
=> Update base image version

Dockerfile
**Checks**
This PR closes #...
=> #39 modify dockerfile version

observer/server.py, observer/static/quick-look.js
**Checks**
This PR closes #36 
Like below.
=> #36 rename topic

pyproject.toml
=> #44 change version number

Dockerfile
=> #46 change dockerfile to necst:v0.6.3

pyproject.toml
=> #50 re-release

Dockerfile
**Checks**
- [] Please debug me
This PR closes #52
=> #52 latest astropy

Dockerfile, pyproject.toml
=> #54 release

Dockerfile, pyproject.toml
=> Release v0.1.9

Dockerfile, pyproject.toml
=> #67 change poetry version

Dockerfile, pyproject.toml
=> #69 delete poetry version

Dockerfile, pyproject.toml
=> #75 change versions

Dockerfile, pyproject.toml
=> #87 release

observer/server.py, observer/static/chart.js, observer/static/index.js, observer/templates/qlook/index.html
**Checks**
This PR closes #13.
=> Add 2-D plot (only encoder now)

pyproject.toml
=> #90 release 023

Dockerfile, pyproject.toml
=> #93 release

observer/static/quick-look.js, observer/templates/qlook/index.html
=> #73 org list

observer/server.py, observer/static/chart.js, observer/static/index.js, observer/templates/qlook/index.html
=> #92 sis 2d
